<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>F1TelemetryLab</AssemblyName>
    <RootNamespace>F1TelemetryLab</RootNamespace>
    <ApplicationIcon></ApplicationIcon>
    <Version>0.7.0</Version>
    <AssemblyVersion>0.7.0.0</AssemblyVersion>
    <FileVersion>0.7.0.0</FileVersion>
    <InformationalVersion>0.7.0</InformationalVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.0.4" />
    <PackageReference Include="Avalonia.Desktop" Version="12.0.4" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.0.4" />
    <PackageReference Include="Microsoft.Data.Sqlite.Core" Version="10.0.9" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="3.0.3" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\..\data\tracks\racenet\**\*.*" Link="data\tracks\racenet\%(RecursiveDir)%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="..\..\data\tracks\Tracks\**\*.*" Link="data\tracks\Tracks\%(RecursiveDir)%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
